/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import javax.swing.JOptionPane;
import config.layout;

/**
 *
 * @author Asus
 */
public class TransaksiList extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiList
     */
    TransaksiClass transaksi = new TransaksiClass();
    
    private void clear(){
        jNamaPenyewa.setText(null);
        jMerk.setText(null);
    }

    public TransaksiList() {
        initComponents();
        layout.Layout(this);
        transaksi.listTransaksi(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblTransaksi = new javax.swing.JTable();
        jFilterTanggal = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jNamaPenyewa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMerk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jStatus = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPilihData = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TRANSAKSI REPORT");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblTransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 950, 202));

        jFilterTanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFilterTanggalPropertyChange(evt);
            }
        });
        getContentPane().add(jFilterTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 174, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true), "Status Sewa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("Nama Penyewa");

        jNamaPenyewa.setEditable(false);

        jLabel3.setText("Merk Mobil");

        jMerk.setEditable(false);

        jLabel4.setText("Status");

        jStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah di Kembalikan", "Belum di Kembalikan" }));

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNamaPenyewa)
                            .addComponent(jMerk)
                            .addComponent(jStatus, 0, 542, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jNamaPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 580, 250));

        jPilihData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Di Kembalikan", "Semua List Transaksi" }));
        jPilihData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jPilihDataItemStateChanged(evt);
            }
        });
        getContentPane().add(jPilihData, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list transaksi.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFilterTanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFilterTanggalPropertyChange
        // TODO add your handling code here:
        try {
            if (jFilterTanggal.getDate() != null) {
                java.util.Date filterTanggal = jFilterTanggal.getDate();
                java.sql.Date tglFilter = new java.sql.Date(filterTanggal.getTime());
                transaksi.listTransaksiFilter(tglFilter);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jFilterTanggalPropertyChange

    private int id_mobil;
    private int id_transaksi;
    private void jTblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblTransaksiMouseClicked
        // TODO add your handling code here:
        try {
            int row = jTblTransaksi.rowAtPoint(evt.getPoint());
            int col = jTblTransaksi.columnAtPoint(evt.getPoint());
            if (row >= 0 && col >= 0) {
                String merk = (String) jTblTransaksi.getValueAt(row, 2);
                String warna = (String) jTblTransaksi.getValueAt(row, 5);
                String status = (String) jTblTransaksi.getValueAt(row, 7);

                id_mobil = (int) jTblTransaksi.getModel().getValueAt(row, 8);
                id_transaksi = (int) jTblTransaksi.getModel().getValueAt(row, 9);
                
//            menampilkan ke textField
                if (status.equals("Sudah di Kembalikan")) {
                    jStatus.setSelectedItem("Sudah di Kembalikan");
                } else {
                    jStatus.setSelectedItem("Belum di Kembalikan");
                }
                jNamaPenyewa.setText(merk);
                jMerk.setText(warna);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Saat Mengambil Data", "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTblTransaksiMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String status = (String) jStatus.getSelectedItem();
        int idMobil = id_mobil;
        int idTransaksi = id_transaksi;
        
        try {
            transaksi.editData(status, idTransaksi, idMobil);
            clear();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPilihDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jPilihDataItemStateChanged
        // TODO add your handling code here:
        if(jPilihData.getSelectedItem() == "Belum Di Kembalikan"){
            transaksi.listTransaksi(false);
        }else if(jPilihData.getSelectedItem() == "Semua List Transaksi"){
            transaksi.listTransaksi(true);
        }
    }//GEN-LAST:event_jPilihDataItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jFilterTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jMerk;
    private javax.swing.JTextField jNamaPenyewa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jPilihData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jStatus;
    public static javax.swing.JTable jTblTransaksi;
    // End of variables declaration//GEN-END:variables
}
