package Transaksi;
//import config.layout;

import Login.LoginClass;
import config.layout;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;

import javax.swing.JOptionPane;

public class Transaksi extends javax.swing.JFrame {

    TransaksiClass transaksi = new TransaksiClass();
    LoginClass login = new LoginClass();

    private int id_user;
    private int id_mobil;
    private int id_pelanggan;

    public Transaksi() {
        initComponents();
        layout.Layout(this);
        transaksi.listMobilTersedia();
        transaksi.listPelanggan();
        jPanelTablePelanggan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMobilTersedia = new javax.swing.JTable();
        jPanelTablePelanggan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePelanggan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMerk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jWarna = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jHargaSewaPerhari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jNamaPenyewa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jNoTelepon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jAlamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTanggalSewa = new com.toedter.calendar.JDateChooser();
        jTanggalKembali = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTotalHarga = new javax.swing.JTextField();
        jJumlahHari = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("MOBIL YANG TERSEDIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 210, -1));

        tblMobilTersedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMobilTersedia.setName("tblMobilTersedia"); // NOI18N
        tblMobilTersedia.setOpaque(false);
        tblMobilTersedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMobilTersediaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMobilTersedia);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 790, 110));

        jTablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePelanggan);

        javax.swing.GroupLayout jPanelTablePelangganLayout = new javax.swing.GroupLayout(jPanelTablePelanggan);
        jPanelTablePelanggan.setLayout(jPanelTablePelangganLayout);
        jPanelTablePelangganLayout.setHorizontalGroup(
            jPanelTablePelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablePelangganLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTablePelangganLayout.setVerticalGroup(
            jPanelTablePelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablePelangganLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTablePelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 420, 240));

        jPanel1.setLayout(null);

        jLabel3.setText("Merk");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 0, 130, 14);

        jMerk.setEditable(false);
        jPanel1.add(jMerk);
        jMerk.setBounds(10, 20, 130, 30);

        jLabel4.setText("Warna");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 50, 130, 20);

        jWarna.setEditable(false);
        jPanel1.add(jWarna);
        jWarna.setBounds(10, 70, 130, 30);

        jLabel1.setText("Harga Sewa Perhari");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 130, 14);

        jHargaSewaPerhari.setEditable(false);
        jPanel1.add(jHargaSewaPerhari);
        jHargaSewaPerhari.setBounds(10, 120, 130, 30);

        jLabel5.setText("Nama Penyewa");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 130, 14);

        jNamaPenyewa.setEditable(false);
        jPanel1.add(jNamaPenyewa);
        jNamaPenyewa.setBounds(10, 170, 130, 30);

        jLabel6.setText("No Telepon");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 200, 130, 14);

        jNoTelepon.setEditable(false);
        jPanel1.add(jNoTelepon);
        jNoTelepon.setBounds(10, 220, 130, 30);

        jLabel7.setText("Alamat");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 250, 130, 20);

        jAlamat.setEditable(false);
        jPanel1.add(jAlamat);
        jAlamat.setBounds(10, 270, 130, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 310));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));
        getContentPane().add(jTanggalSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jTanggalKembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTanggalKembaliPropertyChange(evt);
            }
        });
        getContentPane().add(jTanggalKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel8.setText("Tanggal Kembali");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel9.setText("Tanggal Sewa");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        getContentPane().add(jTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 140, -1));

        jJumlahHari.setText(".....");
        getContentPane().add(jJumlahHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jMenu1.setText("Menu");

        jMenuItem1.setText("List Semua Mobil");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Form Transaksi");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMobilTersediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMobilTersediaMouseClicked
        // TODO add your handling code here:
        jPanelTablePelanggan.setVisible(true);
        try {
            int row = tblMobilTersedia.rowAtPoint(evt.getPoint());
            int col = tblMobilTersedia.columnAtPoint(evt.getPoint());
            if (row >= 0 && col >= 0) {
                String merk = (String) tblMobilTersedia.getValueAt(row, 1);
                String warna = (String) tblMobilTersedia.getValueAt(row, 3);
                String hargaPerH = (String) tblMobilTersedia.getValueAt(row, 5);
                id_mobil = (int) tblMobilTersedia.getModel().getValueAt(row, 6);

                id_user = LoginClass.getIdUsers();

                System.out.println("ini id mobil " + id_mobil);

                System.out.println("ini id users" + id_user);

//            menampilkan ke textField
                jMerk.setText(merk);
                jWarna.setText(warna);
                jHargaSewaPerhari.setText(hargaPerH);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Saat Mengambil Data", "error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_tblMobilTersediaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       int totalHargaSewa = totalHarga;
        
        
        java.util.Date tanggalSewa = jTanggalSewa.getDate();
        java.sql.Date tglSewa = new java.sql.Date(tanggalSewa.getTime());
        
        java.util.Date tanggalKembali = jTanggalKembali.getDate();
        java.sql.Date tglKembali = new java.sql.Date(tanggalKembali.getTime());


        try {
            transaksi.insertData(id_mobil, id_pelanggan, tglSewa, tglKembali, totalHargaSewa, id_user);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePelangganMouseClicked
        // TODO add your handling code here:
        try {
            int row = jTablePelanggan.rowAtPoint(evt.getPoint());
            int col = jTablePelanggan.columnAtPoint(evt.getPoint());
            if (row >= 0 && col >= 0) {
                String nama = (String) jTablePelanggan.getValueAt(row, 0);
                String noTelepon = (String) jTablePelanggan.getValueAt(row, 1);
                String alamat = (String) jTablePelanggan.getValueAt(row, 2);
                id_pelanggan = (int) jTablePelanggan.getModel().getValueAt(row, 3);

                System.out.println("ini id pelanggan" + id_pelanggan);

//            menampilkan ke textField
                jNamaPenyewa.setText(nama);
                jNoTelepon.setText(noTelepon);
                jAlamat.setText(alamat);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Saat Mengambil Data", "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTablePelangganMouseClicked
    int totalHarga;
    private void jTanggalKembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTanggalKembaliPropertyChange
        // TODO add your handling code here:
        try {
            String hargaSewaPerHari = jHargaSewaPerhari.getText();
            int hargaSewaPerHariInt = Integer.parseInt(hargaSewaPerHari);
// Mengambil Format Tanggal
            LocalDate startDate = jTanggalSewa.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate endDate = jTanggalKembali.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
// Hitung jumlah hari antara dua tanggal tersebut
            Period period = Period.between(startDate, endDate);
            int selisihHari = period.getDays();
            if (selisihHari < 0) {
                // Tampilkan pesan peringatan jika hasil perhitungan jumlah hari bernilai negatif
                JOptionPane.showMessageDialog(null, "Periksa lagi tanggal sewa dan tanggal kembali", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            totalHarga = hargaSewaPerHariInt * selisihHari;
            NumberFormat formatter = NumberFormat.getCurrencyInstance();

            jJumlahHari.setText(selisihHari + " Hari");
// Format total harga menjadi uang
            String totalHargaString = formatter.format(totalHarga);
            jTotalHarga.setText(totalHargaString);
        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_jTanggalKembaliPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAlamat;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jHargaSewaPerhari;
    private javax.swing.JLabel jJumlahHari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jMerk;
    private javax.swing.JTextField jNamaPenyewa;
    private javax.swing.JTextField jNoTelepon;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanelTablePelanggan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTablePelanggan;
    private com.toedter.calendar.JDateChooser jTanggalKembali;
    private com.toedter.calendar.JDateChooser jTanggalSewa;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTotalHarga;
    private javax.swing.JTextField jWarna;
    public static javax.swing.JTable tblMobilTersedia;
    // End of variables declaration//GEN-END:variables
}
